services:

  liquibase-product:
    container_name: liquibase-product
    image: liquibase/liquibase
    command: update --changelog-file=changelog.xml --username=user --password=pass --url=jdbc:postgresql://product-db:5432/product
    volumes:
      - ./product/changelog.xml:/liquibase/changelog.xml
      - ./product/scripts:/liquibase/scripts
    networks:
      - backend-net
  
  liquibase-stock:
    container_name: liquibase-stock
    image: liquibase/liquibase
    command: update --changelog-file=changelog.xml --username=user --password=pass --url=jdbc:postgresql://stock-db:5432/stock
    volumes:
      - ./stock/changelog.xml:/liquibase/changelog.xml
      - ./stock/scripts:/liquibase/scripts
    networks:
      - backend-net

  liquibase-sale:
    container_name: liquibase-sale
    image: liquibase/liquibase
    command: update --changelog-file=changelog.xml --username=user --password=pass --url=jdbc:postgresql://sale-db:5432/sale
    volumes:
      - ./sale/changelog.xml:/liquibase/changelog.xml
      - ./sale/scripts:/liquibase/scripts
    networks:
      - backend-net



networks:
  backend-net: 
    external: true
