services:
  db:
    image: postgres:16-alpine
    container_name: ecommerce-sale-db
    environment:
      POSTGRES_DB: ecommerce_sale_db
      POSTGRES_USER: user
      POSTGRES_PASSWORD: pass
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U user"]
      interval: 5s
      timeout: 3s
      retries: 5
    networks:
      - backend-net

networks:
  backend-net:
    external: true
